/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#define PREFIX "/c/Program Files/CodeBlocks/MinGW"
#define EXEC_PREFIX "/c/Program Files/CodeBlocks/MinGW"
#define BINDIR "/c/Program Files/CodeBlocks/MinGW/bin"
#define SBINDIR "/c/Program Files/CodeBlocks/MinGW/sbin"
#define LIBEXECDIR "/c/Program Files/CodeBlocks/MinGW/libexec"
#define DATAROOTDIR "/c/Program Files/CodeBlocks/MinGW/share"
#define DATADIR "/c/Program Files/CodeBlocks/MinGW/share"
#define SYSCONFDIR "/c/Program Files/CodeBlocks/MinGW/etc"
#define SHAREDSTATEDIR "/c/Program Files/CodeBlocks/MinGW/com"
#define LOCALSTATEDIR "/c/Program Files/CodeBlocks/MinGW/var"
#define INCLUDEDIR "/c/Program Files/CodeBlocks/MinGW/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/c/Program Files/CodeBlocks/MinGW/share/doc/regex"
#define INFODIR "/c/Program Files/CodeBlocks/MinGW/share/info"
#define HTMLDIR "/c/Program Files/CodeBlocks/MinGW/share/doc/regex"
#define DVIDIR "/c/Program Files/CodeBlocks/MinGW/share/doc/regex"
#define PDFDIR "/c/Program Files/CodeBlocks/MinGW/share/doc/regex"
#define PSDIR "/c/Program Files/CodeBlocks/MinGW/share/doc/regex"
#define LIBDIR "/c/Program Files/CodeBlocks/MinGW/lib"
#define LOCALEDIR "/c/Program Files/CodeBlocks/MinGW/share/locale"
#define MANDIR "/c/Program Files/CodeBlocks/MinGW/share/man"
#define PKGDATADIR "/c/Program Files/CodeBlocks/MinGW/share/regex"
#define PKGINCLUDEDIR "/c/Program Files/CodeBlocks/MinGW/include/regex"
#define PKGLIBDIR "/c/Program Files/CodeBlocks/MinGW/lib/regex"
#define PKGLIBEXECDIR "/c/Program Files/CodeBlocks/MinGW/libexec/regex"
